
package com.samaylabs.optimus.webservices;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "AgvDeclaration", targetNamespace = "http://WebServices.optimus.samaylabs.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface AgvDeclaration {


    /**
     * 
     * @return
     *     returns java.util.List<com.samaylabs.optimus.webservices.AgvData>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "retriveAgv", targetNamespace = "http://WebServices.optimus.samaylabs.com/", className = "com.samaylabs.optimus.webservices.RetriveAgv")
    @ResponseWrapper(localName = "retriveAgvResponse", targetNamespace = "http://WebServices.optimus.samaylabs.com/", className = "com.samaylabs.optimus.webservices.RetriveAgvResponse")
    @Action(input = "http://WebServices.optimus.samaylabs.com/AgvDeclaration/retriveAgvRequest", output = "http://WebServices.optimus.samaylabs.com/AgvDeclaration/retriveAgvResponse")
    public List<AgvData> retriveAgv();

    /**
     * 
     * @param arg3
     * @param arg2
     * @param arg4
     * @param arg1
     * @param arg0
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "updateAgv", targetNamespace = "http://WebServices.optimus.samaylabs.com/", className = "com.samaylabs.optimus.webservices.UpdateAgv")
    @ResponseWrapper(localName = "updateAgvResponse", targetNamespace = "http://WebServices.optimus.samaylabs.com/", className = "com.samaylabs.optimus.webservices.UpdateAgvResponse")
    @Action(input = "http://WebServices.optimus.samaylabs.com/AgvDeclaration/updateAgvRequest", output = "http://WebServices.optimus.samaylabs.com/AgvDeclaration/updateAgvResponse")
    public boolean updateAgv(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        int arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        String arg2,
        @WebParam(name = "arg3", targetNamespace = "")
        String arg3,
        @WebParam(name = "arg4", targetNamespace = "")
        int arg4);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns com.samaylabs.optimus.webservices.ListWrapper
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "pingAgv", targetNamespace = "http://WebServices.optimus.samaylabs.com/", className = "com.samaylabs.optimus.webservices.PingAgv")
    @ResponseWrapper(localName = "pingAgvResponse", targetNamespace = "http://WebServices.optimus.samaylabs.com/", className = "com.samaylabs.optimus.webservices.PingAgvResponse")
    @Action(input = "http://WebServices.optimus.samaylabs.com/AgvDeclaration/pingAgvRequest", output = "http://WebServices.optimus.samaylabs.com/AgvDeclaration/pingAgvResponse")
    public ListWrapper pingAgv(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        int arg1);

    /**
     * 
     * @param arg3
     * @param arg2
     * @param arg1
     * @param arg0
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "createAgv", targetNamespace = "http://WebServices.optimus.samaylabs.com/", className = "com.samaylabs.optimus.webservices.CreateAgv")
    @ResponseWrapper(localName = "createAgvResponse", targetNamespace = "http://WebServices.optimus.samaylabs.com/", className = "com.samaylabs.optimus.webservices.CreateAgvResponse")
    @Action(input = "http://WebServices.optimus.samaylabs.com/AgvDeclaration/createAgvRequest", output = "http://WebServices.optimus.samaylabs.com/AgvDeclaration/createAgvResponse")
    public boolean createAgv(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        String arg2,
        @WebParam(name = "arg3", targetNamespace = "")
        int arg3);

    /**
     * 
     * @param arg0
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "deleteAgv", targetNamespace = "http://WebServices.optimus.samaylabs.com/", className = "com.samaylabs.optimus.webservices.DeleteAgv")
    @ResponseWrapper(localName = "deleteAgvResponse", targetNamespace = "http://WebServices.optimus.samaylabs.com/", className = "com.samaylabs.optimus.webservices.DeleteAgvResponse")
    @Action(input = "http://WebServices.optimus.samaylabs.com/AgvDeclaration/deleteAgvRequest", output = "http://WebServices.optimus.samaylabs.com/AgvDeclaration/deleteAgvResponse")
    public boolean deleteAgv(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0);

}
