
package com.samaylabs.optimus.webservices;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "AgvService", targetNamespace = "http://WebServices.optimus.samaylabs.com/", wsdlLocation = "http://localhost:9009/Agv?WSDL")
public class AgvService
    extends Service
{

    private final static URL AGVSERVICE_WSDL_LOCATION;
    private final static WebServiceException AGVSERVICE_EXCEPTION;
    private final static QName AGVSERVICE_QNAME = new QName("http://WebServices.optimus.samaylabs.com/", "AgvService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:9009/Agv?WSDL");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        AGVSERVICE_WSDL_LOCATION = url;
        AGVSERVICE_EXCEPTION = e;
    }

    public AgvService() {
        super(__getWsdlLocation(), AGVSERVICE_QNAME);
    }

    public AgvService(WebServiceFeature... features) {
        super(__getWsdlLocation(), AGVSERVICE_QNAME, features);
    }

    public AgvService(URL wsdlLocation) {
        super(wsdlLocation, AGVSERVICE_QNAME);
    }

    public AgvService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, AGVSERVICE_QNAME, features);
    }

    public AgvService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public AgvService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns AgvDeclaration
     */
    @WebEndpoint(name = "AgvPort")
    public AgvDeclaration getAgvPort() {
        return super.getPort(new QName("http://WebServices.optimus.samaylabs.com/", "AgvPort"), AgvDeclaration.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns AgvDeclaration
     */
    @WebEndpoint(name = "AgvPort")
    public AgvDeclaration getAgvPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://WebServices.optimus.samaylabs.com/", "AgvPort"), AgvDeclaration.class, features);
    }

    private static URL __getWsdlLocation() {
        if (AGVSERVICE_EXCEPTION!= null) {
            throw AGVSERVICE_EXCEPTION;
        }
        return AGVSERVICE_WSDL_LOCATION;
    }

}
