
package com.samaylabs.optimus.webservices;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "LogsDefination", targetNamespace = "http://WebServices.optimus.samaylabs.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface LogsDefination {


    /**
     * 
     * @return
     *     returns java.util.List<com.samaylabs.optimus.webservices.Logs>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getOptimusLogs", targetNamespace = "http://WebServices.optimus.samaylabs.com/", className = "com.samaylabs.optimus.webservices.GetOptimusLogs")
    @ResponseWrapper(localName = "getOptimusLogsResponse", targetNamespace = "http://WebServices.optimus.samaylabs.com/", className = "com.samaylabs.optimus.webservices.GetOptimusLogsResponse")
    @Action(input = "http://WebServices.optimus.samaylabs.com/LogsDefination/getOptimusLogsRequest", output = "http://WebServices.optimus.samaylabs.com/LogsDefination/getOptimusLogsResponse")
    public List<Logs> getOptimusLogs();

    /**
     * 
     * @return
     *     returns com.samaylabs.optimus.webservices.ListWrapper
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getUsers", targetNamespace = "http://WebServices.optimus.samaylabs.com/", className = "com.samaylabs.optimus.webservices.GetUsers")
    @ResponseWrapper(localName = "getUsersResponse", targetNamespace = "http://WebServices.optimus.samaylabs.com/", className = "com.samaylabs.optimus.webservices.GetUsersResponse")
    @Action(input = "http://WebServices.optimus.samaylabs.com/LogsDefination/getUsersRequest", output = "http://WebServices.optimus.samaylabs.com/LogsDefination/getUsersResponse")
    public ListWrapper getUsers();

    /**
     * 
     * @param arg2
     * @param arg1
     * @param arg0
     * @return
     *     returns java.util.List<com.samaylabs.optimus.webservices.Logs>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getOptimusLogsDated", targetNamespace = "http://WebServices.optimus.samaylabs.com/", className = "com.samaylabs.optimus.webservices.GetOptimusLogsDated")
    @ResponseWrapper(localName = "getOptimusLogsDatedResponse", targetNamespace = "http://WebServices.optimus.samaylabs.com/", className = "com.samaylabs.optimus.webservices.GetOptimusLogsDatedResponse")
    @Action(input = "http://WebServices.optimus.samaylabs.com/LogsDefination/getOptimusLogsDatedRequest", output = "http://WebServices.optimus.samaylabs.com/LogsDefination/getOptimusLogsDatedResponse")
    public List<Logs> getOptimusLogsDated(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        String arg2);

}
