
package com.samaylabs.optimus.webservices;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "LogsService", targetNamespace = "http://WebServices.optimus.samaylabs.com/", wsdlLocation = "http://localhost:9009/Logs?WSDL")
public class LogsService
    extends Service
{

    private final static URL LOGSSERVICE_WSDL_LOCATION;
    private final static WebServiceException LOGSSERVICE_EXCEPTION;
    private final static QName LOGSSERVICE_QNAME = new QName("http://WebServices.optimus.samaylabs.com/", "LogsService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:9009/Logs?WSDL");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        LOGSSERVICE_WSDL_LOCATION = url;
        LOGSSERVICE_EXCEPTION = e;
    }

    public LogsService() {
        super(__getWsdlLocation(), LOGSSERVICE_QNAME);
    }

    public LogsService(WebServiceFeature... features) {
        super(__getWsdlLocation(), LOGSSERVICE_QNAME, features);
    }

    public LogsService(URL wsdlLocation) {
        super(wsdlLocation, LOGSSERVICE_QNAME);
    }

    public LogsService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, LOGSSERVICE_QNAME, features);
    }

    public LogsService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public LogsService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns LogsDefination
     */
    @WebEndpoint(name = "LogsPort")
    public LogsDefination getLogsPort() {
        return super.getPort(new QName("http://WebServices.optimus.samaylabs.com/", "LogsPort"), LogsDefination.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns LogsDefination
     */
    @WebEndpoint(name = "LogsPort")
    public LogsDefination getLogsPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://WebServices.optimus.samaylabs.com/", "LogsPort"), LogsDefination.class, features);
    }

    private static URL __getWsdlLocation() {
        if (LOGSSERVICE_EXCEPTION!= null) {
            throw LOGSSERVICE_EXCEPTION;
        }
        return LOGSSERVICE_WSDL_LOCATION;
    }

}
