
package com.samaylabs.optimus.webservices;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "OptimusDefination", targetNamespace = "http://WebServices.optimus.samaylabs.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface OptimusDefination {


    /**
     * 
     * @return
     *     returns com.samaylabs.optimus.webservices.ListWrapper
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "startScheduler", targetNamespace = "http://WebServices.optimus.samaylabs.com/", className = "com.samaylabs.optimus.webservices.StartScheduler")
    @ResponseWrapper(localName = "startSchedulerResponse", targetNamespace = "http://WebServices.optimus.samaylabs.com/", className = "com.samaylabs.optimus.webservices.StartSchedulerResponse")
    @Action(input = "http://WebServices.optimus.samaylabs.com/OptimusDefination/startSchedulerRequest", output = "http://WebServices.optimus.samaylabs.com/OptimusDefination/startSchedulerResponse")
    public ListWrapper startScheduler();

    /**
     * 
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "stopNodeServer", targetNamespace = "http://WebServices.optimus.samaylabs.com/", className = "com.samaylabs.optimus.webservices.StopNodeServer")
    @ResponseWrapper(localName = "stopNodeServerResponse", targetNamespace = "http://WebServices.optimus.samaylabs.com/", className = "com.samaylabs.optimus.webservices.StopNodeServerResponse")
    @Action(input = "http://WebServices.optimus.samaylabs.com/OptimusDefination/stopNodeServerRequest", output = "http://WebServices.optimus.samaylabs.com/OptimusDefination/stopNodeServerResponse")
    public boolean stopNodeServer();

    /**
     * 
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "stopScheduler", targetNamespace = "http://WebServices.optimus.samaylabs.com/", className = "com.samaylabs.optimus.webservices.StopScheduler")
    @ResponseWrapper(localName = "stopSchedulerResponse", targetNamespace = "http://WebServices.optimus.samaylabs.com/", className = "com.samaylabs.optimus.webservices.StopSchedulerResponse")
    @Action(input = "http://WebServices.optimus.samaylabs.com/OptimusDefination/stopSchedulerRequest", output = "http://WebServices.optimus.samaylabs.com/OptimusDefination/stopSchedulerResponse")
    public boolean stopScheduler();

    /**
     * 
     * @return
     *     returns com.samaylabs.optimus.webservices.ListWrapper
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "powerStatus", targetNamespace = "http://WebServices.optimus.samaylabs.com/", className = "com.samaylabs.optimus.webservices.PowerStatus")
    @ResponseWrapper(localName = "powerStatusResponse", targetNamespace = "http://WebServices.optimus.samaylabs.com/", className = "com.samaylabs.optimus.webservices.PowerStatusResponse")
    @Action(input = "http://WebServices.optimus.samaylabs.com/OptimusDefination/powerStatusRequest", output = "http://WebServices.optimus.samaylabs.com/OptimusDefination/powerStatusResponse")
    public ListWrapper powerStatus();

    /**
     * 
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "powerStatusKey", targetNamespace = "http://WebServices.optimus.samaylabs.com/", className = "com.samaylabs.optimus.webservices.PowerStatusKey")
    @ResponseWrapper(localName = "powerStatusKeyResponse", targetNamespace = "http://WebServices.optimus.samaylabs.com/", className = "com.samaylabs.optimus.webservices.PowerStatusKeyResponse")
    @Action(input = "http://WebServices.optimus.samaylabs.com/OptimusDefination/powerStatusKeyRequest", output = "http://WebServices.optimus.samaylabs.com/OptimusDefination/powerStatusKeyResponse")
    public int powerStatusKey();

    /**
     * 
     * @param arg3
     * @param arg2
     * @param arg4
     * @param arg1
     * @param arg0
     * @return
     *     returns boolean
     */
    @WebMethod(action = "insert_ticket")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "insertTicket", targetNamespace = "http://WebServices.optimus.samaylabs.com/", className = "com.samaylabs.optimus.webservices.InsertTicket")
    @ResponseWrapper(localName = "insertTicketResponse", targetNamespace = "http://WebServices.optimus.samaylabs.com/", className = "com.samaylabs.optimus.webservices.InsertTicketResponse")
    @Action(input = "insert_ticket", output = "http://WebServices.optimus.samaylabs.com/OptimusDefination/insertTicketResponse")
    public boolean insertTicket(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        long arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        int arg2,
        @WebParam(name = "arg3", targetNamespace = "")
        String arg3,
        @WebParam(name = "arg4", targetNamespace = "")
        String arg4);

    /**
     * 
     * @return
     *     returns java.util.List<com.samaylabs.optimus.webservices.Ticket>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getQueue", targetNamespace = "http://WebServices.optimus.samaylabs.com/", className = "com.samaylabs.optimus.webservices.GetQueue")
    @ResponseWrapper(localName = "getQueueResponse", targetNamespace = "http://WebServices.optimus.samaylabs.com/", className = "com.samaylabs.optimus.webservices.GetQueueResponse")
    @Action(input = "http://WebServices.optimus.samaylabs.com/OptimusDefination/getQueueRequest", output = "http://WebServices.optimus.samaylabs.com/OptimusDefination/getQueueResponse")
    public List<Ticket> getQueue();

    /**
     * 
     * @param arg0
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "removeTicket", targetNamespace = "http://WebServices.optimus.samaylabs.com/", className = "com.samaylabs.optimus.webservices.RemoveTicket")
    @ResponseWrapper(localName = "removeTicketResponse", targetNamespace = "http://WebServices.optimus.samaylabs.com/", className = "com.samaylabs.optimus.webservices.RemoveTicketResponse")
    @Action(input = "http://WebServices.optimus.samaylabs.com/OptimusDefination/removeTicketRequest", output = "http://WebServices.optimus.samaylabs.com/OptimusDefination/removeTicketResponse")
    public boolean removeTicket(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "alterTicket", targetNamespace = "http://WebServices.optimus.samaylabs.com/", className = "com.samaylabs.optimus.webservices.AlterTicket")
    @ResponseWrapper(localName = "alterTicketResponse", targetNamespace = "http://WebServices.optimus.samaylabs.com/", className = "com.samaylabs.optimus.webservices.AlterTicketResponse")
    @Action(input = "http://WebServices.optimus.samaylabs.com/OptimusDefination/alterTicketRequest", output = "http://WebServices.optimus.samaylabs.com/OptimusDefination/alterTicketResponse")
    public boolean alterTicket(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        int arg1);

    /**
     * 
     * @param arg2
     * @param arg1
     * @param arg0
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "setTicketToAgv", targetNamespace = "http://WebServices.optimus.samaylabs.com/", className = "com.samaylabs.optimus.webservices.SetTicketToAgv")
    @ResponseWrapper(localName = "setTicketToAgvResponse", targetNamespace = "http://WebServices.optimus.samaylabs.com/", className = "com.samaylabs.optimus.webservices.SetTicketToAgvResponse")
    @Action(input = "http://WebServices.optimus.samaylabs.com/OptimusDefination/setTicketToAgvRequest", output = "http://WebServices.optimus.samaylabs.com/OptimusDefination/setTicketToAgvResponse")
    public boolean setTicketToAgv(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        int arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        String arg2);

    /**
     * 
     * @return
     *     returns java.util.List<com.samaylabs.optimus.webservices.AgvData>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getAgvInfo", targetNamespace = "http://WebServices.optimus.samaylabs.com/", className = "com.samaylabs.optimus.webservices.GetAgvInfo")
    @ResponseWrapper(localName = "getAgvInfoResponse", targetNamespace = "http://WebServices.optimus.samaylabs.com/", className = "com.samaylabs.optimus.webservices.GetAgvInfoResponse")
    @Action(input = "http://WebServices.optimus.samaylabs.com/OptimusDefination/getAgvInfoRequest", output = "http://WebServices.optimus.samaylabs.com/OptimusDefination/getAgvInfoResponse")
    public List<AgvData> getAgvInfo();

    /**
     * 
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getActiveNode", targetNamespace = "http://WebServices.optimus.samaylabs.com/", className = "com.samaylabs.optimus.webservices.GetActiveNode")
    @ResponseWrapper(localName = "getActiveNodeResponse", targetNamespace = "http://WebServices.optimus.samaylabs.com/", className = "com.samaylabs.optimus.webservices.GetActiveNodeResponse")
    @Action(input = "http://WebServices.optimus.samaylabs.com/OptimusDefination/getActiveNodeRequest", output = "http://WebServices.optimus.samaylabs.com/OptimusDefination/getActiveNodeResponse")
    public int getActiveNode();

    /**
     * 
     * @return
     *     returns com.samaylabs.optimus.webservices.ListWrapper
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "areErrors", targetNamespace = "http://WebServices.optimus.samaylabs.com/", className = "com.samaylabs.optimus.webservices.AreErrors")
    @ResponseWrapper(localName = "areErrorsResponse", targetNamespace = "http://WebServices.optimus.samaylabs.com/", className = "com.samaylabs.optimus.webservices.AreErrorsResponse")
    @Action(input = "http://WebServices.optimus.samaylabs.com/OptimusDefination/areErrorsRequest", output = "http://WebServices.optimus.samaylabs.com/OptimusDefination/areErrorsResponse")
    public ListWrapper areErrors();

    /**
     * 
     * @param arg0
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "uiAbort", targetNamespace = "http://WebServices.optimus.samaylabs.com/", className = "com.samaylabs.optimus.webservices.UiAbort")
    @ResponseWrapper(localName = "uiAbortResponse", targetNamespace = "http://WebServices.optimus.samaylabs.com/", className = "com.samaylabs.optimus.webservices.UiAbortResponse")
    @Action(input = "http://WebServices.optimus.samaylabs.com/OptimusDefination/uiAbortRequest", output = "http://WebServices.optimus.samaylabs.com/OptimusDefination/uiAbortResponse")
    public boolean uiAbort(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0);

    /**
     * 
     * @return
     *     returns com.samaylabs.optimus.webservices.MapWrapper
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getActiveSignals", targetNamespace = "http://WebServices.optimus.samaylabs.com/", className = "com.samaylabs.optimus.webservices.GetActiveSignals")
    @ResponseWrapper(localName = "getActiveSignalsResponse", targetNamespace = "http://WebServices.optimus.samaylabs.com/", className = "com.samaylabs.optimus.webservices.GetActiveSignalsResponse")
    @Action(input = "http://WebServices.optimus.samaylabs.com/OptimusDefination/getActiveSignalsRequest", output = "http://WebServices.optimus.samaylabs.com/OptimusDefination/getActiveSignalsResponse")
    public MapWrapper getActiveSignals();

    /**
     * 
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "isErrors", targetNamespace = "http://WebServices.optimus.samaylabs.com/", className = "com.samaylabs.optimus.webservices.IsErrors")
    @ResponseWrapper(localName = "isErrorsResponse", targetNamespace = "http://WebServices.optimus.samaylabs.com/", className = "com.samaylabs.optimus.webservices.IsErrorsResponse")
    @Action(input = "http://WebServices.optimus.samaylabs.com/OptimusDefination/isErrorsRequest", output = "http://WebServices.optimus.samaylabs.com/OptimusDefination/isErrorsResponse")
    public boolean isErrors();

}
