
package com.samaylabs.optimus.webservices;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "TrackDefination", targetNamespace = "http://WebServices.optimus.samaylabs.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface TrackDefination {


    /**
     * 
     * @param arg3
     * @param arg2
     * @param arg1
     * @param arg0
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "createNode", targetNamespace = "http://WebServices.optimus.samaylabs.com/", className = "com.samaylabs.optimus.webservices.CreateNode")
    @ResponseWrapper(localName = "createNodeResponse", targetNamespace = "http://WebServices.optimus.samaylabs.com/", className = "com.samaylabs.optimus.webservices.CreateNodeResponse")
    @Action(input = "http://WebServices.optimus.samaylabs.com/TrackDefination/createNodeRequest", output = "http://WebServices.optimus.samaylabs.com/TrackDefination/createNodeResponse")
    public boolean createNode(
        @WebParam(name = "arg0", targetNamespace = "")
        long arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        float arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        float arg2,
        @WebParam(name = "arg3", targetNamespace = "")
        int arg3);

    /**
     * 
     * @param arg0
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "deleteNode", targetNamespace = "http://WebServices.optimus.samaylabs.com/", className = "com.samaylabs.optimus.webservices.DeleteNode")
    @ResponseWrapper(localName = "deleteNodeResponse", targetNamespace = "http://WebServices.optimus.samaylabs.com/", className = "com.samaylabs.optimus.webservices.DeleteNodeResponse")
    @Action(input = "http://WebServices.optimus.samaylabs.com/TrackDefination/deleteNodeRequest", output = "http://WebServices.optimus.samaylabs.com/TrackDefination/deleteNodeResponse")
    public boolean deleteNode(
        @WebParam(name = "arg0", targetNamespace = "")
        long arg0);

    /**
     * 
     * @return
     *     returns com.samaylabs.optimus.webservices.Node
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "retriveNode", targetNamespace = "http://WebServices.optimus.samaylabs.com/", className = "com.samaylabs.optimus.webservices.RetriveNode")
    @ResponseWrapper(localName = "retriveNodeResponse", targetNamespace = "http://WebServices.optimus.samaylabs.com/", className = "com.samaylabs.optimus.webservices.RetriveNodeResponse")
    @Action(input = "http://WebServices.optimus.samaylabs.com/TrackDefination/retriveNodeRequest", output = "http://WebServices.optimus.samaylabs.com/TrackDefination/retriveNodeResponse")
    public Node retriveNode();

    /**
     * 
     * @return
     *     returns java.util.List<com.samaylabs.optimus.webservices.Node>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "retriveNodes", targetNamespace = "http://WebServices.optimus.samaylabs.com/", className = "com.samaylabs.optimus.webservices.RetriveNodes")
    @ResponseWrapper(localName = "retriveNodesResponse", targetNamespace = "http://WebServices.optimus.samaylabs.com/", className = "com.samaylabs.optimus.webservices.RetriveNodesResponse")
    @Action(input = "http://WebServices.optimus.samaylabs.com/TrackDefination/retriveNodesRequest", output = "http://WebServices.optimus.samaylabs.com/TrackDefination/retriveNodesResponse")
    public List<Node> retriveNodes();

    /**
     * 
     * @param arg3
     * @param arg2
     * @param arg4
     * @param arg1
     * @param arg0
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "updateNode", targetNamespace = "http://WebServices.optimus.samaylabs.com/", className = "com.samaylabs.optimus.webservices.UpdateNode")
    @ResponseWrapper(localName = "updateNodeResponse", targetNamespace = "http://WebServices.optimus.samaylabs.com/", className = "com.samaylabs.optimus.webservices.UpdateNodeResponse")
    @Action(input = "http://WebServices.optimus.samaylabs.com/TrackDefination/updateNodeRequest", output = "http://WebServices.optimus.samaylabs.com/TrackDefination/updateNodeResponse")
    public boolean updateNode(
        @WebParam(name = "arg0", targetNamespace = "")
        long arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        long arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        float arg2,
        @WebParam(name = "arg3", targetNamespace = "")
        float arg3,
        @WebParam(name = "arg4", targetNamespace = "")
        int arg4);

    /**
     * 
     * @param arg2
     * @param arg1
     * @param arg0
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "createNodeResolver", targetNamespace = "http://WebServices.optimus.samaylabs.com/", className = "com.samaylabs.optimus.webservices.CreateNodeResolver")
    @ResponseWrapper(localName = "createNodeResolverResponse", targetNamespace = "http://WebServices.optimus.samaylabs.com/", className = "com.samaylabs.optimus.webservices.CreateNodeResolverResponse")
    @Action(input = "http://WebServices.optimus.samaylabs.com/TrackDefination/createNodeResolverRequest", output = "http://WebServices.optimus.samaylabs.com/TrackDefination/createNodeResolverResponse")
    public boolean createNodeResolver(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        long arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        String arg2);

    /**
     * 
     * @return
     *     returns java.util.List<com.samaylabs.optimus.webservices.NodeResolver>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "retriveNodeResolver", targetNamespace = "http://WebServices.optimus.samaylabs.com/", className = "com.samaylabs.optimus.webservices.RetriveNodeResolver")
    @ResponseWrapper(localName = "retriveNodeResolverResponse", targetNamespace = "http://WebServices.optimus.samaylabs.com/", className = "com.samaylabs.optimus.webservices.RetriveNodeResolverResponse")
    @Action(input = "http://WebServices.optimus.samaylabs.com/TrackDefination/retriveNodeResolverRequest", output = "http://WebServices.optimus.samaylabs.com/TrackDefination/retriveNodeResolverResponse")
    public List<NodeResolver> retriveNodeResolver();

    /**
     * 
     * @param arg3
     * @param arg2
     * @param arg1
     * @param arg0
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "updateNodeResolver", targetNamespace = "http://WebServices.optimus.samaylabs.com/", className = "com.samaylabs.optimus.webservices.UpdateNodeResolver")
    @ResponseWrapper(localName = "updateNodeResolverResponse", targetNamespace = "http://WebServices.optimus.samaylabs.com/", className = "com.samaylabs.optimus.webservices.UpdateNodeResolverResponse")
    @Action(input = "http://WebServices.optimus.samaylabs.com/TrackDefination/updateNodeResolverRequest", output = "http://WebServices.optimus.samaylabs.com/TrackDefination/updateNodeResolverResponse")
    public boolean updateNodeResolver(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        int arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        long arg2,
        @WebParam(name = "arg3", targetNamespace = "")
        String arg3);

    /**
     * 
     * @param arg0
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "deleteNodeResolver", targetNamespace = "http://WebServices.optimus.samaylabs.com/", className = "com.samaylabs.optimus.webservices.DeleteNodeResolver")
    @ResponseWrapper(localName = "deleteNodeResolverResponse", targetNamespace = "http://WebServices.optimus.samaylabs.com/", className = "com.samaylabs.optimus.webservices.DeleteNodeResolverResponse")
    @Action(input = "http://WebServices.optimus.samaylabs.com/TrackDefination/deleteNodeResolverRequest", output = "http://WebServices.optimus.samaylabs.com/TrackDefination/deleteNodeResolverResponse")
    public boolean deleteNodeResolver(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0);

    /**
     * 
     * @param arg3
     * @param arg2
     * @param arg1
     * @param arg0
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "createEdge", targetNamespace = "http://WebServices.optimus.samaylabs.com/", className = "com.samaylabs.optimus.webservices.CreateEdge")
    @ResponseWrapper(localName = "createEdgeResponse", targetNamespace = "http://WebServices.optimus.samaylabs.com/", className = "com.samaylabs.optimus.webservices.CreateEdgeResponse")
    @Action(input = "http://WebServices.optimus.samaylabs.com/TrackDefination/createEdgeRequest", output = "http://WebServices.optimus.samaylabs.com/TrackDefination/createEdgeResponse")
    public boolean createEdge(
        @WebParam(name = "arg0", targetNamespace = "")
        long arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        long arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        double arg2,
        @WebParam(name = "arg3", targetNamespace = "")
        float arg3);

    /**
     * 
     * @return
     *     returns java.util.List<com.samaylabs.optimus.webservices.Edge>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "retriveEdge", targetNamespace = "http://WebServices.optimus.samaylabs.com/", className = "com.samaylabs.optimus.webservices.RetriveEdge")
    @ResponseWrapper(localName = "retriveEdgeResponse", targetNamespace = "http://WebServices.optimus.samaylabs.com/", className = "com.samaylabs.optimus.webservices.RetriveEdgeResponse")
    @Action(input = "http://WebServices.optimus.samaylabs.com/TrackDefination/retriveEdgeRequest", output = "http://WebServices.optimus.samaylabs.com/TrackDefination/retriveEdgeResponse")
    public List<Edge> retriveEdge();

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "deleteEdge", targetNamespace = "http://WebServices.optimus.samaylabs.com/", className = "com.samaylabs.optimus.webservices.DeleteEdge")
    @ResponseWrapper(localName = "deleteEdgeResponse", targetNamespace = "http://WebServices.optimus.samaylabs.com/", className = "com.samaylabs.optimus.webservices.DeleteEdgeResponse")
    @Action(input = "http://WebServices.optimus.samaylabs.com/TrackDefination/deleteEdgeRequest", output = "http://WebServices.optimus.samaylabs.com/TrackDefination/deleteEdgeResponse")
    public boolean deleteEdge(
        @WebParam(name = "arg0", targetNamespace = "")
        long arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        long arg1);

    /**
     * 
     * @param arg3
     * @param arg2
     * @param arg5
     * @param arg4
     * @param arg1
     * @param arg0
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "updateEdge", targetNamespace = "http://WebServices.optimus.samaylabs.com/", className = "com.samaylabs.optimus.webservices.UpdateEdge")
    @ResponseWrapper(localName = "updateEdgeResponse", targetNamespace = "http://WebServices.optimus.samaylabs.com/", className = "com.samaylabs.optimus.webservices.UpdateEdgeResponse")
    @Action(input = "http://WebServices.optimus.samaylabs.com/TrackDefination/updateEdgeRequest", output = "http://WebServices.optimus.samaylabs.com/TrackDefination/updateEdgeResponse")
    public boolean updateEdge(
        @WebParam(name = "arg0", targetNamespace = "")
        long arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        long arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        long arg2,
        @WebParam(name = "arg3", targetNamespace = "")
        long arg3,
        @WebParam(name = "arg4", targetNamespace = "")
        double arg4,
        @WebParam(name = "arg5", targetNamespace = "")
        float arg5);

    /**
     * 
     * @return
     *     returns java.util.List<java.lang.Long>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getAnchors", targetNamespace = "http://WebServices.optimus.samaylabs.com/", className = "com.samaylabs.optimus.webservices.GetAnchors")
    @ResponseWrapper(localName = "getAnchorsResponse", targetNamespace = "http://WebServices.optimus.samaylabs.com/", className = "com.samaylabs.optimus.webservices.GetAnchorsResponse")
    @Action(input = "http://WebServices.optimus.samaylabs.com/TrackDefination/getAnchorsRequest", output = "http://WebServices.optimus.samaylabs.com/TrackDefination/getAnchorsResponse")
    public List<Long> getAnchors();

    /**
     * 
     * @return
     *     returns java.util.List<java.lang.Long>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getAllAnchors", targetNamespace = "http://WebServices.optimus.samaylabs.com/", className = "com.samaylabs.optimus.webservices.GetAllAnchors")
    @ResponseWrapper(localName = "getAllAnchorsResponse", targetNamespace = "http://WebServices.optimus.samaylabs.com/", className = "com.samaylabs.optimus.webservices.GetAllAnchorsResponse")
    @Action(input = "http://WebServices.optimus.samaylabs.com/TrackDefination/getAllAnchorsRequest", output = "http://WebServices.optimus.samaylabs.com/TrackDefination/getAllAnchorsResponse")
    public List<Long> getAllAnchors();

}
